### ISSUE TITLE
ISO 8601 dates

### ISSUE THREAD

**Issue by alanlesc1** [hengsin/idempiere-rest#5]
Hi Heng Sin,

Wouldn't be better to have dates as ISO 8601 format instead of getting it from DisplayType.getDateFormat()? Ex: 2012-04-23T18:25:43.511Z

Here's why:
It's human readable but also succinct
It sorts correctly
It includes fractional seconds, which can help re-establish chronology
It conforms to ISO 8601
ISO 8601 has been well-established internationally for more than a decade
ISO 8601 is endorsed by W3C, RFC3339, and XKCD

If ok, I could provide a pull request.
Alan

**Comment by hengsin** [comment]
Hi Alan,

Sounds ok to me. Please send in your pull request, will check it out. Do note the need to support date only format as well (without the time portion).

Regards,
Low

**Comment by alanlesc1** [comment]
Note that it instantiate a new java.text.SimpleDateFormat to every method call (the same as DisplayType.getDateFormat() does). This is not the best, as SimpleDateFormat is quite expensive to instantiate, and it is also not thread-safe, so a static field is not an option. Local thread or the use of synchronized maybe are not good options here (as we expect rest responses to be fast). I will open a new issue to consider using  java.time.format.DateTimeFormatter and/or java.time.LocalTime. This would be relevant to idempiere also, as optimization.
